#!/bin/bash
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%30s%s%-10s\n' "COMANDOS DISPONÍVEIS:" ; tput sgr0 ; echo ""
tput setaf 2 ; tput bold ; printf '%s' "criarusuario " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Cria usuário com limite de conexão e data de vencimento"
tput setaf 2 ; tput bold ; printf '%s' "apagar " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Apaga usuário, caso dê errado, use: userdel -r usuario"
tput setaf 2 ; tput bold ; printf '%s' "mudarsenha " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Muda a senha do usuário selecionado"
tput setaf 2 ; tput bold ; printf '%s' "mudardata " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Mudar a data de expiração de um usuário"
tput setaf 2 ; tput bold ; printf '%s' "mudarlimite " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Mudar limite de logins do usuario"
tput setaf 2 ; tput bold ; printf '%s' "monitor " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Verifica quem está conectado e quantos logins está usando"
tput setaf 2 ; tput bold ; printf '%s' "sshlimiter " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Limita as conexões de acordo com o limite dado a ele"
tput setaf 2 ; tput bold ; printf '%s' "apps " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Como configurar os aplicativos: Eproxy e KpnTunnel Ultimate"
tput setaf 2 ; tput bold ; printf '%s' "Ctrl+c " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Interromper comandos e voltar ao Prompt"
tput setaf 5 ; tput bold ; printf '%s' "loginseguro " ; tput setaf 7 ; printf '%s' "- " ; tput setaf 3 ; echo "Login CRIPTOGRAFADO impossível de ser quebrado, sem uso da senha do usuário, assim quem abrir seu arquivo ñ poderá fazer nada. Vendo o método por R$ 100, se ñ tem a grana, ñ terá o método."
tput sgr0
echo ""
